export const DATA_REQUEST = 'DATA_REQUEST';
export const SET_PROJECT_DATA = 'SET_PROJECT_DATA';
export const IS_FAVORITE_REQUEST = 'IS_FAVORITE_REQUEST';
export const SET_IS_FAVORITE = 'SET_IS_FAVORITE';
