export const USER_DATA_REQUEST = 'DATA_REQUEST';
export const USER_PROJECTS_REQUEST = 'DATA_REQUEST';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_USER_PROJECTS = 'SET_USER_PROJECTS';
